---
title: "New study confirms the power of Deinosuchus and its 'teeth the size of bananas'"
description: |
  Alongside dinosaurs lived a giant crocodylian which was able to prey on them.
author:
  - name: Lucien Marchand
    url: {}
date: 12-09-2020
output:
  distill::distill_article:
    self_contained: false
---

# SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT
Source of the article : [https://www.sciencedaily.com/releases/2020/08/200810141002.htm?fbclid=IwAR1g83Akera8DbkBzrG3Xb5crAQOyOoheO_rKt-8Lte94H1u5IfQ-bTjWgA]

Source of the original study : [https://www.tandfonline.com/doi/full/10.1080/02724634.2020.1767638?scroll=top&needAccess=true]

Published on The 10th of August 2020

Word count: 532 words

# VOCABULARY
| Word from the text | Synonym/definition in English | French translation |
|------------------- |----------------------------- |--------------------|
|entitled | called | intitulé|
|to range| vary within limits| varrier|
|shallow |not deep| peu profond|
| present-day |current| actuel|
|though|however|cependant|
|genera (plural of genus)|(biological subdivision)|genre|
|to outweigh| be heavier than|être plus lourd que|
|alongside |next to|à coté de|
|remains of|what is left of |des restes de|
|to shed light on|to explain|éclaircir|
|edge|extremity| bord|
|given that|seeing that|vu que|
|in spite of|despite|malgré|
|snout|animal's nose|museau|
|broad|wide|large|
|inflated |filled with air or gas|gonflé|
|tip|end|extrémité|


# ANALYSIS TABLE ABOUT THE STUDY
|             |             |
|-------------|-------------|
|Researchers ?|Adam P. Cossette & Christopher A. Brochu|
|Published in ? When ?|Originally published in the Journal of Vertebrate Paleontology, Received 10 Oct 2018, Accepted 28 Jan 2020, Published online: 29 Jul 2020|
|General topic|Description of the Deinosuchus, known to be one of the largest crocodylian genera that ever lived|
|Procedure/What was examined| - Dinosaurs' bones and turtles' shells with bite marks. 
- snout inflated at the front around the nose like any other crocodylian.
- skull.
- large holes present at the tip of the snout.|
|Conclusions/Discovery|- Present-day crocodylians aren't living fossils but they evolved.
- Deinosuchus seems to have been an opportunistic predator and everything on its habitat was on its menu.|
|Remaining questions|- The reason for its enlarged nose is unknown.
- The reason for its extinction remains unknown. 
- We don't know what their two large holes at the tip of the snout were for.|
