---
title: "Article 1 : Megalodon's hugeness was 'off-the-scale', even for a shark"
description: |
  Let's dive through the greatest sharks that ever lived.
author:
  - name: Lucien Marchand
    url: {}
date: 10-25-2020
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# SOURCE OF THE ARTICLE WITH PUBLICATION DATE AND WORD COUNT
Source of the article : [https://www.livescience.com/megalodon-big-for-a-shark.html?fbclid=IwAR1XNX8S9wUDIqgcC2lQi2PZRXZu6CzT86kE3qG548TLz-Gc1OtNsChtOrk]

Published on The 5th of October 2020

Word count: 720 words

# VOCABULARY
| Word from the text | Synonym/definition in English | French translation |
|------------------- |----------------------------- |--------------------|
|Among | Inside of | Parmi
|Relatives | Cousins | Parents |
|Girth | Mass | Corpulence |
|Outlier | Different from normal | Cas particulier |
|substantially | a lot | considérablement |
|pipsqueaks | little person unimportant | Avorton, demi-portion |
|whopping | very big | énorme |
|plentiful | abundant | abondant |
|rather than | instead | plutôt que |
|scarce | rare | rare |
|save for | except for | Sauf pour |
|Bearing (to bear) | | Porter |
|behavior | attitude | comportement |
|Hatching (to hatch) | to come out of an egg | éclore |
|siblings | Brothers and sisters | frères et soeurs |
|to dwarf | To be bigger than | Faire paraître petit |
|gap | break | fossé |
|remain | continue to be | rester |
|to unsettle | to disturb | Perturber |

# ANALYSIS TABLE ABOUT THE STUDY
|             |             |
|-------------|-------------|
|Researchers ?|Kenshu Shimada|
|Published in ? When ?|October the 5th in the journal Historical Biology, Originally published on Live Science.|
|General topic|The Megalodon (Otodus megalodon) had a whopping size compared with the other sharks, witch could reach up to 15 meters (against 6m for the great white shark).|
|Procedure/What was examined|To evaluate how tall was a prehistoric shark, we can't use fossils of their body because "shark skeleton are made of cartilage (rather than bones)" witch fossilize scarcely ever. However, fossilized tooth are plentiful and the scientifics "Shimada and his colleagues developed  a new tool for calculating body length : an equation representing the actual relationship between body length and tooth size in lamniforms".|
|Conclusions/Discovery|The scientists found that "many extinct lamniform sharks were quite large" and each of it's genera and held at least one shark species that was more than 6m in length. However, most of these lamniform didn't grow more than 7 meters in length, but Odotus megalodon could reach 15m in length, witch means that there is a huge gap between the Meg and the other lamniforms.|
|Remaining questions|Even if we think that the shark's supersize can be fuel by their reproductive strategy (involving that the early-hatching embryos eat siblings' eggs), we still don't know why the Meg could be so huge. Moreover, causes of the extinct of this shark still "remain unsettled".|
